### ISSUE TITLE
Implement initialization from saved JSON project

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#23]

**Comment by im-Amitto** [comment]
@Kristin33 isn't it same as the import project from JSON file that we already have in the project tab

**Comment by ankit204** [comment]
@im-Amitto, is converting a project to JSON and restoring from JSON documented somewhere? I ask because there are some cases like permissions for mic and loading sounds in audio buffer that need proper handling.

**Comment by im-Amitto** [comment]
@ankit204 I am not sure if I am the right person to do the documentation for that because what I did was actually use the redux store in the project-editor front-end which was already there when I started on this repo. I only added the functionality to download and upload that JSON object.

**Comment by rbdannenberg** [comment]
Hi all,

Quick update: we have a version of project save and restore functionality checked-in in GitHub. Please file issues if you find any.

Thanks,
Ankit

**Comment by rbdannenberg** [comment]
Connect a signalgen to speaker. Set dropdown to Sine Wave and Vol: to 10.
Save the project.
Restore the project: There will be no sound because the Sine Wave is not selected. The volume will be maximum because the Vol: value is not restored.

There is no Project Save or Save As... menu item (that's probably covered in another issue as well).

**Comment by ankit204** [comment]
This issue is specific to ScSignalGen. Fixed with: https://github.com/rbdannenberg/soundcool/commit/6562bf03af2c4ba0cf5b1b9efb40d4ce11635655 and 0481d6c6de82641a1ac70d25cb92d216c92d6980.
