### ISSUE TITLE
soundcool main surface html5

### ISSUE THREAD

**Issue by masaeal** [rbdannenberg/soundcool#31]
[Soundcool surface html.zip](https://github.com/rbdannenberg/soundcool/files/4379715/Soundcool.surface.html.zip)

[AddBlock.zip](https://github.com/rbdannenberg/soundcool/files/4379717/AddBlock.zip)
[error modify script.zip]

(https://github.com/rbdannenberg/soundcool/files/4379875/error.modify.script.zip)

**Comment by im-Amitto** [comment]
@masaeal 
The error is caused by the `husky` and the reason could be that you don't have `git` installed on your system or husky can't recognize the folder as a valid repo.
The best way to solve this problem is
1. Check if git is installed (simply run `git` and you will get some valid response if it's installed). If not, download and install it.
2. If the problem is not related to the git installation which is rare then I would suggest you use git to clone the repo in your system instead of downloading and extracting it. To do that simply run the following command in the terminal/cmd/Powershell.
```
 git clone https://github.com/rbdannenberg/soundcool.git
```

**Comment by im-Amitto** [comment]
@rbdannenberg @ankit204 @Kristin33 
Are we using husky anywhere in the project? if not better to remove it.

**Comment by anusfoil** [comment]
I am not using it; feel free to remove it

**Comment by rbdannenberg** [comment]
remove husky is now in #42
