### ISSUE TITLE
Project functionalities 

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#51]
We need to specify the buttons on the project page before implement it

- open?
- save / save as?
- new?
- share? 
- delete? 
- view also in the menu? 

all buttons should exist no matter whether users are logged in?  
use a dropdown menu?

**Comment by rbdannenberg** [comment]
-  New -- creates an empty editor window
-  Open -- opens what is currently called "ProjectMenu," a list of projects with Actions choices of Edit, Share, Copy, and Delete
      o Note the addition of "Copy" - this should prompt for a name and description. Equivalent to "Open" followed by "Save As...", but the project is not actually opened in the editor.
- Save -- saves the current project from the editor. If user is not editing a saved project, the user is prompted for a name and description.
- Save As... -- prompts for a name and description (default to current name with " copy 1", " copy 2", etc. appended) and then saves under the new name.
- Export -- allows user to download a .json representation of the project. This can be imported using the Import menu item.
- Import -- prompts to upload a .json file representation of a project and adds it to the list of projects.
- Use Floating View/Use Column View -- changes the view mode to/from floating or columns.
- It would be nice to have recent projects appear in the drop-down menu as well to allow a single selection to open a recently edited project.
---------------------------
The issue was about specifications, so I'll consider this the spec and close the issue.
